name = "care4paws-backend"
main = "index.js" # Ensure this points to your backend script file
type = "javascript"

[[kv_namespaces]]
binding = "UsersKV" # This must match the binding name in your code
id = "YOUR_KV_NAMESPACE_ID" # Replace with your actual KV namespace ID from the Cloudflare dashboard