name = "care4pawsofficial2"
type = "javascript"
account_id = "abc123def456gh789"
workers_dev = true
compatibility_date = "2025-03-26"

[build]
command = "npm install && npm run build"
cwd = "./"
watch_dir = "./"

[env.production]
workers_dev = false
zone_id = "xyz987uvw654ts321"
route = "care4paws.example.com/*"