compatibility_date = "2025-04-12"

[site]
bucket = "." # Serve files from the root folder.
[env.production]
workers_dev = true # Enables deployment to workers.dev subdomain.

[account]
email = "Care4pawsneaionia@gmail.com"