name = "care4paws-backend"
main = "src/index.js"  # Update this if your entry file is located elsewhere
type = "javascript"

[[kv_namespaces]]
binding = "UsersKV"  # Optional: Remove if you're not using Workers KV
id = "YOUR_KV_NAMESPACE_ID"  # Replace with your actual KV Namespace ID or leave empty for now